---
title: "Arima_Tutorial_AirPassenger"
output: html_document
---

## データ準備
```{r}
AirPassengers
```

```{r}
train <- window(AirPassengers, end=c(1959, 12))
```

## データプロット
```{r}
plot(train,type="o")
```
## 自己相関・偏自己相関
```{r}
library(forecast)
ggtsdisplay(train)
```
# 対数変換
```{r}
log_AirPassengers <- log(train)
plot(log_AirPassengers,type="o")
```

## 差分(階差)データ
```{r}
diff(log_AirPassengers,lag = 1)
```

## 差分データの表示 
```{r}
diff_log_AirPassengers = diff(log_AirPassengers,lag=1)
plot(diff_log_AirPassengers)
```
## ARIMAモデルの構築
```{r}
model.0 <- arima(log_AirPassengers,order = c(1,0,1))
```

## 残差の自己相関 
```{r}
tsdiag(model.0)
```

## 自動ARIMAモデルの構築
```{r}
model.1 <- auto.arima(
    log_AirPassengers,
    ic="aic",
    trace=T,
    stepwise=F,
    approximation=F,
    start.p=0,
    start.q=0,
    start.P=0,
    start.Q=0
)
```

## 残差の自己相関 
```{r}
checkresiduals(model.0)
checkresiduals(model.1)
```
## 残差の正規性
```{r}
library(tseries)
jarque.bera.test(resid(model.1))
```

## ARIMAによる予測
```{r}
plot(
forecast(model.1, level = c(30,95), h = 12),
#xlim=c(1959, 1961),
lwd=1
)
lines(log(AirPassengers),type="o")
```

